{% set name = "bluesky" %}
{% set version = "1.6.0rc2" %}
{% set sha256 = "e33265296e6782419468a753fdc0a36435e872a8377de48c690ec093759350a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cycler
    - databroker
    - doct
    - event-model >=1.10.0
    - historydict
    - ipython
    - lmfit
    - matplotlib
    - msgpack-numpy
    - msgpack-python
    - numpy
    - ophyd
    - pyzmq
    - super_state_machine
    - toolz
    - tqdm
    - zict

test:
  imports:
    - bluesky
    - bluesky.plans
    - bluesky.callbacks

about:
  home: https://blueskyproject.io
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Python data collection interface for experimental science'
  description: 'A Python data collection interface for experimental science'
  doc_url: https://blueskyproject.io/bluesky
  dev_url: https://github.com/bluesky/bluesky
